### ISSUE TITLE
Errors: Methods not found: 'ListView.separated' & 'AnnotatedRegion'

### ISSUE THREAD

**Issue by RakhimyanTim** [jogboms/tailor_made#45]
Hello!
I've tried to check this project, but reseived some errors. Can you explain/ help how I can to solve there. Many thanks

1) Methods not found: 'ListView.separated' on pages:
- lib/pages/contacts/contacts.dart:108:15
- lib/pages/jobs/ui/contact_lists.dart:34:17
- lib/pages/jobs/ui/measures.dart:34:21

2) Method not found: 'AnnotatedRegion' on pages:
- lib/ui/avatar_app_bar.dart:104:16
- lib/pages/gallery/gallery_view.dart:60:16

![flutter_doctor](https://user-images.githubusercontent.com/13000093/42722142-3fc91e84-8760-11e8-9bce-0222a4575a50.png)
![flutter_error](https://user-images.githubusercontent.com/13000093/42722143-40073412-8760-11e8-8de0-d784f9a87031.png)

**Comment by RakhimyanTim** [comment]
Is it related  with firebase rules/settings?

**Comment by jogboms** [comment]
Not really @RakhimyanTim, I'm on the master branch.

**Comment by jogboms** [comment]
@RakhimyanTim My flutter development environment is on the master branch channel
