### ISSUE TITLE
More Detail on how to setup workspace? 

### ISSUE THREAD

**Issue by mamatagelanee07** [jogboms/tailor_made#85]
I am trying to set up a workspace, and getting few errors. Do any specific steps we need to set up before running the flutter project. 

Note: Flutter is already installed and running fine with other applications. 

<img width="1105" alt="Screenshot 2019-03-23 at 12 34 11" src="https://user-images.githubusercontent.com/8694335/54866108-022dbc00-4d68-11e9-87c7-e9f7b856ec95.png">

**Comment by jogboms** [comment]
Hello @mamatagelanee07 

I attached vscode launch scripts. If you want to do this on the CMD, you would need to specify the `--flavor`. They are two flavors, `dev` and `prod`.

```bash
flutter run -t lib/main_dev.dart --flavor dev
```

There are also `make` scripts if you wish to just build.

**Comment by 926** [comment]
Hi @jogboms,

Sorry again,
I updated config with  signingConfig signingConfigs.debug

But i still a Gradle error : 
Execution failed for task ':app:processDevDebugGoogleServices'. 

File google-services.json is missing. The Google Services Plugin cannot function without it.

**Comment by jogboms** [comment]
@926 You need one of those. You can set up on Firebase.

**Comment by 926** [comment]
Thank you again for quick reply.
1. Set-up dedicated firebase app.
2. Configured google-services.json in the android/app
3. Edited the build files accordingly
4. run flutter run -t lib/main_dev.dart --flavor dev

=> 

Execution failed for task ':app:processDevDebugGoogleServices'.         
> No matching client found for package name 'io.github.jogboms.tailormade.dev'

**Comment by ffoliveira** [comment]
> Thank you again for quick reply.
> 
> 1. Set-up dedicated firebase app.
> 2. Configured google-services.json in the android/app
> 3. Edited the build files accordingly
> 4. run flutter run -t lib/main_dev.dart --flavor dev
> 
> =>
> 
> Execution failed for task ':app:processDevDebugGoogleServices'.
> 
> > No matching client found for package name 'io.github.jogboms.tailormade.dev'

You have to create a firebase application that matchs the application ID with your application. I think it is in the build.gradle file at /android/app folder. in the applicationId field.

I did it and compiled without that error.

Now I have an error when running. It might be how the Firebase application need to be configured. I didn't find how and what to configure at firebase console. Any ideas ?

**Comment by jogboms** [comment]
@ffoliveira thanks for the added info.

@926 Since flavors are being used, it means you have to create apps for both `io.github.jogboms.tailormade` and `io.github.jogboms.tailormade.dev` with the former being for if you are building using the `prod` flavor and the latter being the `dev` flavor.

**Comment by ffoliveira** [comment]
There is some help in how to configure Firebase at google console ?

I have an error when running. It might be how the Firebase application need to be configured. I didn't find how and what to configure at firebase console. **Any ideas** ?

After the Splash screen it gives the following error in console:

`E/flutter ( 5243): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type '() => void' is not a subtype of type '(dynamic) => dynamic'
E/flutter ( 5243): #0      _invokeErrorHandler (dart:async/async_error.dart:16:23)
`

**Comment by 926** [comment]
@jogboms did you add firebase at the beginning of the project or is it possible to trace an early commit without it to avoid the errors it yields ?

**Comment by jogboms** [comment]
Thinking about it again, i think the best way to do this would be to share my dev configuration for firebase together with the repo.

**Comment by 926** [comment]
Whatever works

**Comment by ffoliveira** [comment]
In another flutter app, that used Firebase, I had to insert some data into a collection manually before it started to work.

**Comment by jogboms** [comment]
The configurations have been added to the develop branch.

**Comment by ffoliveira** [comment]
> @jogboms did you add firebase at the beginning of the project or is it possible to trace an early commit without it to avoid the errors it yields ?

The error that happened with my copy was just this issue:

https://github.com/dart-lang/sdk/issues/35812

**Comment by jogboms** [comment]
Interesting @mamatagelanee07 if i knew how the stacktrace looks like, maybe i can help.

**Comment by yeshwanthvshenoy** [comment]
@jogboms Went through above errors and solutions but on current master, getting this error

`Compiler message:
lib/rebloc/app_state.dart:11:6: Error: Error when reading 'lib/rebloc/app_state.g.dart': No such file or directory
part 'app_state.g.dart';`

not only this one but many others similar to this. Almost every model file. Any ideas what is missing?

**Comment by tobyokeke** [comment]
Try running the command below.

`	flutter packages pub run build_runner build --delete-conflicting-outputs
`

**Comment by yeshwanthvshenoy** [comment]
@jogboms Thanks for the quick response. Now I cleared that error getting

`/Users/yeshwanths/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.8.2+3/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java:8: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;`

I haven't modified any build.gradle files. I did some googling, it appears something related to AndroidX. Any idea how to tackle this?

**Comment by sudo-kaizen** [comment]
Could this be added to the README or a a separate markdown file be created for this?
