### ISSUE TITLE
android/key.properties

### ISSUE THREAD

**Issue by 926** [jogboms/tailor_made#86]
Hi @jogboms !
The android app is fantastic, but I failed to run from my android device : 

FAILURE: Build failed with an exception.
tailor_made/android/key.properties (No such file or directory)

here is the exact code in line 10 : 
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

Any clues on why this is failing ?

**Comment by jogboms** [comment]
@926 see #85 if it solves the issue.

**Comment by 926** [comment]
Thanks for the quick reply.
No it is not for release but to understand how you build the **SlideDownItem** in : 
    lib/widgets/screens/measures/_partials/measures_slide_block.dart

![photo_2019-04-12_14-11-10](https://user-images.githubusercontent.com/14161798/56043458-d54c4380-5d2c-11e9-98e1-8bef94fecc6e.jpg)

Regarding the error, I assume the lines to comment out are from :

android/app/build.gradle

After commenting out, using : 
flutter run -t lib/main_dev.dart --flavor dev

 yields another error at line 47 :
    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }

Should I also edit the gradle file at line 55 to remove buildTypes release ?

**Comment by jogboms** [comment]
Yes @926 comment out those lines as well.

Nice.
