### ISSUE TITLE
Error starting the application 

### ISSUE THREAD

**Issue by ffoliveira** [jogboms/tailor_made#87]
> Thank you again for quick reply.
> 
> 1. Set-up dedicated firebase app.
> 2. Configured google-services.json in the android/app
> 3. Edited the build files accordingly
> 4. run flutter run -t lib/main_dev.dart --flavor dev
> 
> =>
> 
> Execution failed for task ':app:processDevDebugGoogleServices'.
> 
> > No matching client found for package name 'io.github.jogboms.tailormade.dev'

You have to create a firebase application that matchs the application ID with your application. I think it is in the build.gradle file at /android/app folder. in the applicationId field.

I did it and compiled without that error.

Now I have an error when running. It might be how the Firebase application need to be configured. I didn't find how and what to configure at firebase console. Any ideas ?

After the Splash screen it gives the following error in console:

`E/flutter ( 5243): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type '() => void' is not a subtype of type '(dynamic) => dynamic'
E/flutter ( 5243): #0      _invokeErrorHandler (dart:async/async_error.dart:16:23)
`

_Originally posted by @ffoliveira in https://github.com/jogboms/tailor_made/issues/85#issuecomment-484504062_

I think it might be only Firebase configuration. But not sure

**Comment by jogboms** [comment]
See my [Comment](https://github.com/jogboms/tailor_made/issues/85#issuecomment-484813361) if it maybe throws more light.
