### ISSUE TITLE
Action is defined in multiple libraries

### ISSUE THREAD

**Issue by Effekt3r** [jogboms/tailor_made#89]
when launching the flutter app I get the following:
Compiler message:
../flutter/.pub-cache/hosted/pub.dartlang.org/rebloc-0.2.1/lib/src/widgets.dart:10:1: Error: 'Action' is imported from both 'package:flutter/src/widgets/actions.dart' and 'package:rebloc/src/engine.dart'.
import 'engine.dart';

What am I missing??

**Comment by tobyokeke** [comment]
import 'package:flutter/src/widgets/actions.dart' hide Action;

You should hide the action class from flutter widgets in the file with the issue which is the widgets.dart file from reboc. Alternatively check the rebloc repo if there's an update that fixes that already.

**Comment by jogboms** [comment]
@Effekt3r Or better yet, update the `rebloc` package to `0.3.0+1`.
